max_width = 80
tab_spaces = 4
hard_tabs = false
fn_single_line = true
match_block_trailing_comma = true
normalize_comments = true
wrap_comments = true
merge_imports = false
reorder_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
normalize_doc_attributes = true
report_fixme = "Always"
edition = "2018"
